[workspace]
resolver = "2"
members = [
    "meilisearch",
    "meilitool",
    "meilisearch-types",
    "meilisearch-auth",
    "meili-snap",
    "index-scheduler",
    "dump",
    "file-store",
    "permissive-json-pointer",
    "milli",
    "filter-parser",
    "flatten-serde-json",
    "json-depth-checker",
    "benchmarks",
    "fuzzers",
    "tracing-trace",
    "xtask",
    "build-info",
]

[workspace.package]
version = "1.9.0"
rust-version = "1.77.0"
authors = [
    "Quentin de Quelen <quentin@dequelen.me>",
    "Clément Renault <clement@meilisearch.com>",
]
description = "Meilisearch HTTP server"
homepage = "https://meilisearch.com"
readme = "README.md"
edition = "2021"
license = "MIT"

[profile.release]
codegen-units = 1

[profile.dev.package.flate2]
opt-level = 3

[profile.dev.package.grenad]
opt-level = 3
[profile.dev.package.roaring]
opt-level = 3

[profile.dev.package.lindera-ipadic-builder]
opt-level = 3
[profile.dev.package.encoding]
opt-level = 3
[profile.dev.package.yada]
opt-level = 3

[profile.release.package.lindera-ipadic-builder]
opt-level = 3
[profile.release.package.encoding]
opt-level = 3
[profile.release.package.yada]
opt-level = 3

[profile.bench.package.lindera-ipadic-builder]
opt-level = 3
[profile.bench.package.encoding]
opt-level = 3
[profile.bench.package.yada]
opt-level = 3
